### ISSUE TITLE
Create the Use-Cases

### ISSUE THREAD

**Issue by Aparnamaurya** [SoftwareEngineeringProjectCS331/EventManagerComprehensiveComparator#5]
As per the Wikipedia definition, A _use case diagram_ can be defined as, representation of a user's interaction with the system showing the relationship between the user and the different use cases in which the user is involved.

Add the required Use-cases diagram to the repository.

**Comment by palakkapoor22** [comment]
Done and Uploaded!

**Comment by Aparnamaurya** [comment]
done!
